#pragma once

namespace Ids {
	enum class Ids {
		vazio = 0,
		fase_floresta,
		plataforma,
		fundo_floresta,
		oriana,
		oriana_anda,
		oriana_para,
		oriana_pula,
		oriana_cai,
		oriana_ataca,
		oriana_morre,
		goblin_bate,
		goblin_atira,
		goblin_anda,
		goblin_para,
		goblin_ataca1,
		goblin_ataca2,
		goblin_ataca3,
		goblin_morre,
		goblin_tomaDano,
		esqueleto_bate,
		esqueleto_atira,
		esqueleto_ataca1,
		esqueleto_ataca2,
		esqueleto_ataca3,
		esqueleto_para,
		esqueleto_anda,
		esqueleto_morre,
		esqueleto_tomaDano,
		animagus,
		animagus_ataca1,
		animagus_ataca2,
		animagus_anda,
		animagus_para,
		animagus_morre,
		animagus_tomaDano,
		projetil,
		goblin_bomba,
		esqueleto_bomba
	};
}